import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./custom css/animations.css";
import "./custom css/utils.css";
import { ClerkProvider } from "@clerk/nextjs";
import Script from "next/script";
import ScrollToTop from "@/components/scrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
         <Script
        src="https://checkout.razorpay.com/v1/checkout.js"
        strategy="afterInteractive"
      />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ScrollToTop>{children}</ScrollToTop>
        </body>
      </html>
    </ClerkProvider>
  );
}
